In [244]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect("ecommerce.db")

print("Database connected successfully!")

Database connected successfully!

In [245]:
tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name;
""", conn)

tables

          name
0    customers
1  order_items
2       orders
3     products

In [246]:
pd.read_sql_query("""
SELECT *
FROM customers;
""", conn)

   customer_id customer_name       city country
0            1        Saurav  Bangalore   India
1            2         Rahul     Mumbai   India
2            3         Priya      Delhi   India
3            4          Amit    Chennai   India
4            5          Neha  Hyderabad   India
5            6         Arjun       Pune   India
6            7         Sneha    Kolkata   India
7            8        Vikram  Bangalore   India

In [247]:
pd.read_sql_query("""
SELECT *
FROM products;
""", conn)

   product_id  product_name     category    price
0         101        Laptop  Electronics  55000.0
1         102    Smartphone  Electronics  30000.0
2         103    Headphones  Electronics   2500.0
3         104  Office Chair    Furniture   7000.0
4         105          Desk    Furniture  12000.0
5         106      Backpack  Accessories   1800.0
6         107      Keyboard  Electronics   1500.0
7         108         Mouse  Electronics    900.0

In [248]:
pd.read_sql_query("""
SELECT *
FROM orders;
""", conn)

   order_id  customer_id  order_date  total_amount
0      1001            1  2026-01-05       57400.0
1      1002            2  2026-01-10       30000.0
2      1003            3  2026-01-15        9500.0
3      1004            4  2026-02-03       12000.0
4      1005            5  2026-02-12       32500.0
5      1006            6  2026-02-20        7000.0
6      1007            7  2026-03-05        1800.0
7      1008            8  2026-03-15       16300.0
8      1009            1  2026-03-20        4000.0
9      1010            3  2026-04-02       55000.0

In [249]:
pd.read_sql_query("""
SELECT *
FROM order_items;
""", conn)

    order_item_id  order_id  product_id  quantity  unit_price
0               1      1001         101         1     55000.0
1               2      1001         107         1      1500.0
2               3      1001         108         1       900.0
3               4      1002         102         1     30000.0
4               5      1003         104         1      7000.0
5               6      1003         106         1      1800.0
6               7      1003         108         1       700.0
7               8      1004         105         1     12000.0
8               9      1005         102         1     30000.0
9              10      1005         103         1      2500.0
10             11      1006         104         1      7000.0
11             12      1007         106         1      1800.0
12             13      1008         105         1     12000.0
13             14      1008         106         1      1800.0
14             15      1008         103         1      2500.0
15             16      1009         103         1      2500.0
16             17      1009         107         1      1500.0
17             18      1010         101         1     55000.0

In [250]:
query = """
SELECT
    customer_id,
    customer_name,
    city
FROM customers;
"""

result = pd.read_sql_query(query, conn)

result

   customer_id customer_name       city
0            1        Saurav  Bangalore
1            2         Rahul     Mumbai
2            3         Priya      Delhi
3            4          Amit    Chennai
4            5          Neha  Hyderabad
5            6         Arjun       Pune
6            7         Sneha    Kolkata
7            8        Vikram  Bangalore

In [251]:
query = """
SELECT
    customer_id,
    customer_name,
    city
FROM customers
WHERE city = 'Bangalore';
"""

result = pd.read_sql_query(query, conn)

result

   customer_id customer_name       city
0            1        Saurav  Bangalore
1            8        Vikram  Bangalore

In [252]:
query = """
SELECT
    product_name,
    category,
    price
FROM products
ORDER BY price DESC;
"""

result = pd.read_sql_query(query, conn)

result

   product_name     category    price
0        Laptop  Electronics  55000.0
1    Smartphone  Electronics  30000.0
2          Desk    Furniture  12000.0
3  Office Chair    Furniture   7000.0
4    Headphones  Electronics   2500.0
5      Backpack  Accessories   1800.0
6      Keyboard  Electronics   1500.0
7         Mouse  Electronics    900.0

In [253]:
query = """
SELECT
    category,
    SUM(price) AS total_product_value
FROM products
GROUP BY category
ORDER BY total_product_value DESC;
"""

result = pd.read_sql_query(query, conn)

result

      category  total_product_value
0  Electronics              89900.0
1    Furniture              19000.0
2  Accessories               1800.0

In [254]:
query = """
SELECT
    SUM(quantity * unit_price) AS total_revenue
FROM order_items;
"""

result = pd.read_sql_query(query, conn)

result

   total_revenue
0       225500.0

In [255]:
query = """
PRAGMA table_info(order_items);
"""

result = pd.read_sql_query(query, conn)

result

   cid           name     type  notnull dflt_value  pk
0    0  order_item_id  INTEGER        0       None   1
1    1       order_id  INTEGER        0       None   0
2    2     product_id  INTEGER        0       None   0
3    3       quantity  INTEGER        0       None   0
4    4     unit_price     REAL        0       None   0

In [256]:
query = """
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

result

   product_name  total_quantity_sold
0    Headphones                    3
1      Backpack                    3
2        Laptop                    2
3    Smartphone                    2
4  Office Chair                    2
5          Desk                    2
6      Keyboard                    2
7         Mouse                    2

In [257]:
query = """
SELECT
    p.category,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, conn)

result

      category  total_revenue
0  Electronics       182100.0
1    Furniture        38000.0
2  Accessories         5400.0

In [258]:
query = """
PRAGMA table_info(orders);
"""

result = pd.read_sql_query(query, conn)

result

   cid          name     type  notnull dflt_value  pk
0    0      order_id  INTEGER        0       None   1
1    1   customer_id  INTEGER        0       None   0
2    2    order_date     TEXT        0       None   0
3    3  total_amount     REAL        0       None   0

In [259]:
query = """
SELECT
    AVG(total_amount) AS average_order_value
FROM orders;
"""

result = pd.read_sql_query(query, conn)

result

   average_order_value
0              22550.0

In [260]:
query = """
SELECT
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

result

  customer_name  total_orders
0        Saurav             2
1         Priya             2
2         Rahul             1
3          Amit             1
4          Neha             1
5         Arjun             1
6         Sneha             1
7        Vikram             1

In [261]:
query = """
SELECT
    c.customer_name,
    SUM(o.total_amount) AS total_spent
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

result

  customer_name  total_spent
0         Priya      64500.0
1        Saurav      61400.0
2          Neha      32500.0
3         Rahul      30000.0
4        Vikram      16300.0
5          Amit      12000.0
6         Arjun       7000.0
7         Sneha       1800.0

In [262]:
query = """
SELECT
    order_id,
    customer_id,
    order_date,
    total_amount
FROM orders
ORDER BY total_amount DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

result

   order_id  customer_id  order_date  total_amount
0      1001            1  2026-01-05       57400.0
1      1010            3  2026-04-02       55000.0
2      1005            5  2026-02-12       32500.0
3      1002            2  2026-01-10       30000.0
4      1008            8  2026-03-15       16300.0
5      1004            4  2026-02-03       12000.0
6      1003            3  2026-01-15        9500.0
7      1006            6  2026-02-20        7000.0
8      1009            1  2026-03-20        4000.0
9      1007            7  2026-03-05        1800.0

In [263]:
query = """
CREATE VIEW IF NOT EXISTS customer_spending AS
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders,
    SUM(o.total_amount) AS total_spent
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;
"""

conn.execute(query)
conn.commit()

print("View 'customer_spending' is ready!")

View 'customer_spending' is ready!

In [264]:
query = """
CREATE INDEX IF NOT EXISTS idx_orders_customer_id
ON orders(customer_id);
"""

conn.execute(query)
conn.commit()

print("Index 'idx_orders_customer_id' is ready!")

Index 'idx_orders_customer_id' is ready!

In [265]:
query = """
PRAGMA index_list('orders');
"""

result = pd.read_sql_query(query, conn)

result

   seq                    name  unique origin  partial
0    0  idx_orders_customer_id       0      c        0

In [266]:
query = """
EXPLAIN QUERY PLAN
SELECT
    c.customer_name,
    o.order_id,
    o.total_amount
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.customer_id = 1;
"""

result = pd.read_sql_query(query, conn)

result

   id  parent  notused                                             detail
0   4       0        0       SEARCH c USING INTEGER PRIMARY KEY (rowid=?)
1   8       0        0  SEARCH o USING INDEX idx_orders_customer_id (c...

In [267]:
query = """
SELECT
    c.customer_id,
    c.customer_name,
    o.order_id,
    o.total_amount
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
ORDER BY c.customer_id;
"""

result = pd.read_sql_query(query, conn)

result

   customer_id customer_name  order_id  total_amount
0            1        Saurav      1001       57400.0
1            1        Saurav      1009        4000.0
2            2         Rahul      1002       30000.0
3            3         Priya      1003        9500.0
4            3         Priya      1010       55000.0
5            4          Amit      1004       12000.0
6            5          Neha      1005       32500.0
7            6         Arjun      1006        7000.0
8            7         Sneha      1007        1800.0
9            8        Vikram      1008       16300.0

In [268]:
import sqlite3

print("SQLite version:", sqlite3.sqlite_version)

SQLite version: 3.45.1

In [269]:
query = """
SELECT
    o.order_id,
    o.customer_id,
    c.customer_name,
    o.order_date,
    o.total_amount
FROM orders o
RIGHT JOIN customers c
    ON o.customer_id = c.customer_id
ORDER BY c.customer_id;
"""

result = pd.read_sql_query(query, conn)

result

   order_id  customer_id customer_name  order_date  total_amount
0      1001            1        Saurav  2026-01-05       57400.0
1      1009            1        Saurav  2026-03-20        4000.0
2      1002            2         Rahul  2026-01-10       30000.0
3      1003            3         Priya  2026-01-15        9500.0
4      1010            3         Priya  2026-04-02       55000.0
5      1004            4          Amit  2026-02-03       12000.0
6      1005            5          Neha  2026-02-12       32500.0
7      1006            6         Arjun  2026-02-20        7000.0
8      1007            7         Sneha  2026-03-05        1800.0
9      1008            8        Vikram  2026-03-15       16300.0

In [270]:
query = """
SELECT
    c.customer_name,
    o.order_id,
    o.order_date,
    o.total_amount
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
ORDER BY o.total_amount DESC;
"""

result = pd.read_sql_query(query, conn)

result

  customer_name  order_id  order_date  total_amount
0        Saurav      1001  2026-01-05       57400.0
1         Priya      1010  2026-04-02       55000.0
2          Neha      1005  2026-02-12       32500.0
3         Rahul      1002  2026-01-10       30000.0
4        Vikram      1008  2026-03-15       16300.0
5          Amit      1004  2026-02-03       12000.0
6         Priya      1003  2026-01-15        9500.0
7         Arjun      1006  2026-02-20        7000.0
8        Saurav      1009  2026-03-20        4000.0
9         Sneha      1007  2026-03-05        1800.0

In [271]:
query = """
SELECT *
FROM customer_spending
ORDER BY total_spent DESC;
"""

result = pd.read_sql_query(query, conn)

result

   customer_id customer_name  total_orders  total_spent
0            3         Priya             2      64500.0
1            1        Saurav             2      61400.0
2            5          Neha             1      32500.0
3            2         Rahul             1      30000.0
4            8        Vikram             1      16300.0
5            4          Amit             1      12000.0
6            6         Arjun             1       7000.0
7            7         Sneha             1       1800.0

In [272]:
query = """
SELECT
    category,
    AVG(price) AS average_price
FROM products
GROUP BY category
ORDER BY average_price DESC;
"""

result = pd.read_sql_query(query, conn)

result

      category  average_price
0  Electronics        17980.0
1    Furniture         9500.0
2  Accessories         1800.0

In [273]:
sql_content = """
-- Elevate Labs - Task 3: SQL for Data Analysis

-- SELECT
SELECT customer_id, customer_name, city
FROM customers;

-- WHERE
SELECT customer_id, customer_name, city
FROM customers
WHERE city = 'Bangalore';

-- ORDER BY
SELECT product_name, category, price
FROM products
ORDER BY price DESC;

-- GROUP BY + SUM
SELECT category, SUM(price) AS total_product_value
FROM products
GROUP BY category
ORDER BY total_product_value DESC;

-- GROUP BY + AVG
SELECT category, AVG(price) AS average_price
FROM products
GROUP BY category
ORDER BY average_price DESC;

-- Total Revenue
SELECT SUM(quantity * unit_price) AS total_revenue
FROM order_items;

-- Top-Selling Products
SELECT p.product_name, SUM(oi.quantity) AS total_quantity_sold
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 10;

-- Revenue by Category
SELECT p.category, SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Average Order Value
SELECT AVG(total_amount) AS average_order_value
FROM orders;

-- Top Customers by Orders
SELECT c.customer_name, COUNT(o.order_id) AS total_orders
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC
LIMIT 10;

-- Top Customers by Spending
SELECT c.customer_name, SUM(o.total_amount) AS total_spent
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 10;

-- Highest-Value Orders
SELECT order_id, customer_id, order_date, total_amount
FROM orders
ORDER BY total_amount DESC
LIMIT 10;

-- Subquery
SELECT c.customer_name, SUM(o.total_amount) AS total_spent
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING SUM(o.total_amount) > (
    SELECT AVG(customer_total)
    FROM (
        SELECT customer_id, SUM(total_amount) AS customer_total
        FROM orders
        GROUP BY customer_id
    )
)
ORDER BY total_spent DESC;

-- INNER JOIN
SELECT c.customer_name, o.order_id, o.order_date, o.total_amount
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
ORDER BY o.total_amount DESC;

-- LEFT JOIN
SELECT c.customer_id, c.customer_name, o.order_id, o.total_amount
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
ORDER BY c.customer_id;

-- RIGHT JOIN
SELECT o.order_id, o.customer_id, c.customer_name, o.order_date, o.total_amount
FROM orders o
RIGHT JOIN customers c ON o.customer_id = c.customer_id
ORDER BY c.customer_id;

-- CREATE VIEW
CREATE VIEW IF NOT EXISTS customer_spending AS
SELECT c.customer_id, c.customer_name,
       COUNT(o.order_id) AS total_orders,
       SUM(o.total_amount) AS total_spent
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

-- Use View
SELECT *
FROM customer_spending
ORDER BY total_spent DESC;

-- CREATE INDEX
CREATE INDEX IF NOT EXISTS idx_orders_customer_id
ON orders(customer_id);

-- Query Optimization
EXPLAIN QUERY PLAN
SELECT c.customer_name, o.order_id, o.total_amount
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
WHERE o.customer_id = 1;
"""

with open("task3_sql_queries.sql", "w", encoding="utf-8") as f:
    f.write(sql_content)

print("task3_sql_queries.sql created successfully!")

task3_sql_queries.sql created successfully!

In [274]:
readme_content = '''
# Elevate Labs - Task 3: SQL for Data Analysis

## Project Overview

This project was completed as part of the Elevate Labs Data Analyst Internship.

The objective of this task is to use SQL queries to extract, analyze, and interpret data from an e-commerce database.

## Tools Used

- SQLite
- Python
- Google Colab
- Pandas
- SQL

## Database

The project uses an e-commerce database named `Ecommerce_SQL_Database`.

### Tables

The database contains four tables:

1. `customers` - Customer information
2. `products` - Product information
3. `orders` - Order information
4. `order_items` - Individual items included in orders

## SQL Concepts Covered

The following SQL concepts were implemented:

- SELECT
- WHERE
- ORDER BY
- GROUP BY
- SUM()
- AVG()
- COUNT()
- INNER JOIN
- LEFT JOIN
- RIGHT JOIN
- Subqueries
- Creating SQL Views
- Creating Indexes
- Query Optimization using EXPLAIN QUERY PLAN

## Analysis Performed

The analysis includes:

- Filtering customers by city
- Sorting products by price
- Calculating product value by category
- Calculating average product price by category
- Calculating total revenue
- Identifying top-selling products
- Calculating revenue by category
- Calculating average order value
- Identifying customers with the most orders
- Identifying highest-spending customers
- Finding highest-value orders
- Identifying customers spending above the average
- Demonstrating INNER, LEFT, and RIGHT JOINs
- Creating and querying a customer spending view
- Creating an index on orders.customer_id
- Using EXPLAIN QUERY PLAN for query optimization

## Project Structure

elevate-labs-task-3-sql-data-analysis/
|
|-- README.md
|
|-- sql/
|   |-- task3_sql_queries.sql
|
|-- database/
|   |-- ecommerce.db
|
|-- screenshots/
    |-- 01_select.png
    |-- 02_where.png
    |-- 03_order_by.png
    |-- 04_group_by_sum.png
    |-- 05_group_by_avg.png
    |-- 06_total_revenue.png
    |-- 07_inner_join.png
    |-- 08_left_join.png
    |-- 09_right_join.png
    |-- 10_subquery.png
    |-- 11_view.png
    |-- 12_index_optimization.png

## Deliverables

- SQL query file
- SQLite database
- Query output screenshots
- README documentation

## Conclusion

This task demonstrates practical SQL skills for data analysis, including data retrieval, aggregation, joins, subqueries, views, indexing, and query optimization using an e-commerce database.
'''

with open("README.md", "w", encoding="utf-8") as f:
    f.write(readme_content)

print("README.md created successfully!")

README.md created successfully!